f = open('text.txt','r',encoding='utf-8')
#print(f.read())
#print(f.read(6))
#print(f.readline())
f.close()
#a = open('text.txt','w',encoding='utf-8')
f = open('text.txt','a',encoding='utf-8')
f.write('четвертый')
f.writelines(['\nпятый','\nшестой'])